### ISSUE TITLE
So many failing branches?

### ISSUE THREAD

**Issue by rusefillc** [ChibiOS/ChibiOS-Contrib#313] opened 2022-02-01 01:31 UTC
As of today:

https://github.com/ChibiOS/ChibiOS-Contrib fails tests, no changes for a few months
https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-20.3.x fails tests, no changes for a few months
https://github.com/ChibiOS/ChibiOS-Contrib/commits/chibios-21.6.x fails tests, no changes for a few months

Is build system broken or is not just not important?

**Comment by zykrah** [comment] 2022-02-01 19:27
It's falling due to a few reasons... See #310

**Comment by rusefillc** [comment] 2022-02-01 19:29
https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-20.3.x is probably not caused by #310

**Comment by zykrah** [comment] 2022-02-01 20:08
That PR just addresses the issues in both 20.3.x and 21.6.x that stop them from passing CI, at the same time as updating them to support the latest ChibiOS.

**Comment by rusefillc** [comment] 2022-02-01 20:10
![image](https://user-images.githubusercontent.com/48498823/152043472-fce0392c-6cb2-4fcf-991b-8059b62f2a59.png)

https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-20.3.x failing state would probably not be changed #310 since it's before target branch of #310?

**Comment by fpoussin** [comment] 2022-02-06 18:52
Failing branch can be caused by changed in the Chibios base code.
Seems like some RP2040 files were moved or removed.

As for 21.6.x, it's not been fixed, we'll move on to 21.11 directly.

**Comment by rusefillc** [comment] 2022-02-06 22:14
what has changed for https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-20.3.x ? why is https://github.com/ChibiOS/ChibiOS-Contrib/tree/chibios-20.3.x no longer red?

**Comment by fpoussin** [comment] 2022-02-06 22:24
I've cleared some stall GH actions workflows

**Comment by fpoussin** [comment] 2022-02-06 22:28
all fixed now

**Closed as completed by fpoussin** 2022-02-06 22:28 UTC
